name: image_editor_pro
description: Image Editor Plugin with filters, drawing, text and emoji like stories.
version: 0.0.1
homepage: https://github.com/Moeed366/

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.1.2
  screenshot: ^3.0.0
  extended_image: ^9.1.0
  image: ^4.5.2
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.0
  reorderables: ^0.6.0
  permission_handler: ^11.1.0
  flex_color_picker: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
